[package]
name = "hyperlocal"
version = "0.6.0"
authors = ["softprops <d.tangren@gmail.com>"]
description = "Hyper bindings for unix domain sockets"
homepage = "https://github.com/softprops/hyperlocal"
repository = "https://github.com/softprops/hyperlocal"
keywords = ["hyper", "unix", "sockets", "http"]
license = "MIT"
readme = "README.md"
edition = "2018"

[dependencies]
futures01 = { package = "futures", version = "0.1" }
futures-preview = { version = "0.3.0-alpha.17", features = ["compat"] }
hex = "0.3"
hyper = "0.12"
tokio = "0.1"
tokio-io = "0.1"
tokio-uds = "0.2"
